---
- name: Configure routing
  hosts: all
  become: yes
  tasks:
    # Base
    - name: Enable IP forwarding
      sysctl:
        name: net.ipv4.ip_forward
        value: '1'
        state: present
        reload: yes

    - name: Allow all input temporarily
      iptables:
        chain: INPUT
        policy: ACCEPT

    - name: Flush all tables
      iptables:
        flush: yes

    - name: Flush all NAT tables
      iptables:
        table: nat
        flush: yes

    - name: Drop all routing by default
      iptables:
        chain: FORWARD
        policy: DROP

    - name: Forward established connections
      iptables:
        chain: FORWARD
        ctstate: ESTABLISHED,RELATED
        jump: ACCEPT

    - name: Allow established connections
      iptables:
        chain: INPUT
        ctstate: ESTABLISHED,RELATED
        jump: ACCEPT

    - name: Allow traffic to localhost
      iptables:
        chain: INPUT
        in_interface: lo
        jump: ACCEPT

    - name: Allow SSH in from internet
      iptables:
        chain: INPUT
        protocol: tcp
        destination_port: 22
        in_interface: eth0
        jump: ACCEPT

    - name: Allow VPN in from internet
      iptables:
        chain: INPUT
        protocol: udp
        destination_port: 51820
        in_interface: eth0
        jump: ACCEPT

    # Management
    - name: Allow input from management
      iptables:
        chain: INPUT
        source: 10.250.0.0/16
        jump: ACCEPT

    - name: Allow input from ICE management
      iptables:
        chain: INPUT
        source: 10.253.0.0/16
        jump: ACCEPT

    - name: Forward from management
      iptables:
        chain: FORWARD
        source: 10.250.0.0/16
        jump: ACCEPT

    - name: Forward from management
      iptables:
        chain: FORWARD
        source: 10.253.0.0/16
        jump: ACCEPT

    # Players
    - name: Allow forward to players
      iptables:
        chain: FORWARD
        destination: 10.150.0.0/16
        jump: ACCEPT

    - name: Allow forward to ICE players
      iptables:
        chain: FORWARD
        destination: 10.254.0.0/16
        jump: ACCEPT

    - name: NAT to players from any
      iptables:
        table: nat
        chain: POSTROUTING
        destination: 10.150.0.0/16
        jump: MASQUERADE

    - name: NAT to ICE players from any
      iptables:
        table: nat
        chain: POSTROUTING
        destination: 10.254.0.0/16
        jump: MASQUERADE

    # Challenge specific for players
    - name: Forward traffic from players to target HTTP server
      iptables:
        chain: FORWARD
        source: 10.150.0.0/16
        destination: 10.151.1.100/32
        protocol: tcp
        destination_port: 80
        jump: ACCEPT

    - name: Forward traffic from ICE players to target HTTP server
      iptables:
        chain: FORWARD
        source: 10.254.0.0/16
        destination: 10.151.1.100/32
        protocol: tcp
        destination_port: 80
        jump: ACCEPT

    - name: Forward traffic from players to dev HTTP server
      iptables:
        chain: FORWARD
        source: 10.150.0.0/16
        destination: 10.151.1.101/32
        protocol: tcp
        destination_port: 80
        jump: ACCEPT

    - name: Forward traffic from ICE players to dev HTTP server
      iptables:
        chain: FORWARD
        source: 10.254.0.0/16
        destination: 10.151.1.101/32
        protocol: tcp
        destination_port: 80
        jump: ACCEPT

    - name: Forward traffic from players to dev RDP
      iptables:
        chain: FORWARD
        source: 10.150.0.0/16
        destination: 10.151.1.101/32
        protocol: tcp
        destination_port: 3389
        jump: ACCEPT

    - name: Forward traffic from ICE players to dev RDP
      iptables:
        chain: FORWARD
        source: 10.254.0.0/16
        destination: 10.151.1.101/32
        protocol: tcp
        destination_port: 3389
        jump: ACCEPT

    - name: Forward traffic from players to dev SMB
      iptables:
        chain: FORWARD
        source: 10.150.0.0/16
        destination: 10.151.1.101/32
        protocol: tcp
        destination_port: 445
        jump: ACCEPT

    - name: Forward traffic from ICE players to dev SMB
      iptables:
        chain: FORWARD
        source: 10.254.0.0/16
        destination: 10.151.1.101/32
        protocol: tcp
        destination_port: 445
        jump: ACCEPT

    - name: Allow flag server on 54137 from 10.151.1.100
      iptables:
        chain: INPUT
        protocol: tcp
        destination_port: 54137
        source: 10.151.1.100/32
        jump: ACCEPT

    # Save
    - name: Drop all input by default
      iptables:
        chain: INPUT
        policy: DROP

    - name: Save iptables rules
      command: service netfilter-persistent save

    # Temporary for set
    - name: Allow all forward temporarily
      iptables:
        chain: FORWARD
        policy: ACCEPT