---
# Load data
- import_playbook: data.yml

- name: Setup forests
  hosts: all
  vars:
    domain: "{{lab.hosts[dict_key].domain}}"
    domain_username: "{{credentials[domain].username}}"
    domain_password: "{{credentials[domain].password}}"
    netbios_name: "{{lab.domains[domain].netbios_name}}"
  tasks:
    - name: Ensure that domain exists
      microsoft.ad.domain:
        domain_netbios_name: "{{netbios_name}}"
        dns_domain_name: "{{domain}}"
        safe_mode_password: "{{domain_password}}"
      register: check_domain

    - name: Reboot to complete domain creation
      win_reboot:
        reboot_timeout: 900
        post_reboot_delay: 100
      when: check_domain.changed

    - name: Wait for ADWS to start
      ansible.windows.win_service:
        name: adws
        state: started
        start_mode: auto
      retries: 10
      delay: 60

    - name: Install ActiveDirectoryDsc
      win_psmodule:
        name: ActiveDirectoryDSC
        state: present

    - name: Ensure {{domain_username}} exists
      microsoft.ad.user:
        name: "{{domain_username}}"
        password: "{{domain_password}}"
        state: present
        password_never_expires: yes
        user_cannot_change_password: yes
        enabled: yes
      retries: 10
      delay: 60

    - name: "Ensure {{domain_username}} is in Enterprise Admins"
      microsoft.ad.group:
        name: "Enterprise Admins"
        members:
          add:
            - "{{domain_username}}"
        state: present

    - name: "Ensure {{domain_username}} is in Domain Admins"
      microsoft.ad.group:
        name: "Domain Admins"
        members:
          add:
            - "{{domain_username}}"
        state: present