---
# Load data
- import_playbook: data.yml

- name: Add dummy flag for dev
  hosts: dev
  tasks:
    - name: Add flag folder
      win_file:
        path: "C:\\flag"
        state: directory

    - name: Copy flag file
      win_copy:
        src: "flag.dummy.txt"
        dest: "C:\\flag\\flag.txt"

    - name: Allow NT AUTHORITY\System to read flag directory
      win_acl:
        inherit: "ContainerInherit, ObjectInherit"
        path: "C:\\flag"
        rights: "ListDirectory, Read, ReadAndExecute"
        type: allow
        user: "NT AUTHORITY\\System"

    - name: Allow Administrators to read flag directory
      win_acl:
        inherit: "ContainerInherit, ObjectInherit"
        path: "C:\\flag"
        rights: "ListDirectory, Read, ReadAndExecute"
        type: allow
        user: "Administrators"

    - name: Set owner of directory to NT AUTHORITY\System
      win_owner:
        path: "C:\\flag"
        user: "NT AUTHORITY\\System"

    - name: Remove inheritance from flag directory
      win_acl_inheritance:
        path: "C:\\flag"
        state: absent

- name: Setup dynamic flag for target
  hosts: target
  tasks:
    - name: Add flag folder
      win_file:
        path: "C:\\flag"
        state: directory

    - name: Allow NT AUTHORITY\System to read/write flag directory
      win_acl:
        inherit: "ContainerInherit, ObjectInherit"
        path: "C:\\flag"
        rights: "ListDirectory, Read, ReadAndExecute, Write"
        type: allow
        user: "NT AUTHORITY\\System"

    - name: Allow Administrators to read/write flag directory
      win_acl:
        inherit: "ContainerInherit, ObjectInherit"
        path: "C:\\flag"
        rights: "ListDirectory, Read, ReadAndExecute, Write"
        type: allow
        user: "Administrators"

    - name: Set owner of directory to NT AUTHORITY\System
      win_owner:
        path: "C:\\flag"
        user: "NT AUTHORITY\\System"

    - name: Remove inheritance from flag directory
      win_acl_inheritance:
        path: "C:\\flag"
        state: absent
