---
# Load data
- import_playbook: data.yml

- name: Basic server configuration
  hosts: all
  vars:
    hostname: "{{lab.hosts[dict_key].hostname}}"
  tasks:
    - name: Change the hostname
      win_hostname:
        name: "{{hostname}}"
      register: win_hostname

    - name: Hide Server manager on login
      win_regedit:
        path: HKLM:\Software\Microsoft\ServerManager
        name: DoNotOpenServerManagerAtLogon
        data: 1
        type: dword

    - name: Disable Windows Smart screen
      win_regedit:
        path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer
        name: SmartScreenEnabled
        data: "Off"
        type: string

    - name: Disable Windows update
      script: no_update.ps1

    - name: Disable firewall
      community.windows.win_firewall:
        state: disabled
        profiles:
        - Domain
        - Private
        - Public

    - name: Disable Network Location wizard
      win_regedit:
        path: HKLM:\SYSTEM\CurrentControlSet\Control\Network\NewNetworkWindowOff

    - name: Reboot if needed
      win_reboot:
        reboot_timeout: 600
        post_reboot_delay: 30
      when: win_hostname.reboot_required

    - name: Upgrade module PowerShellGet to fix accept license issue on last windows ansible version
      win_shell: |
        [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
        Install-PackageProvider -Name NuGet -Force -MinimumVersion 2.8.5.201
        Install-Module PowerShellGet -Force

    - name: Check for ComputerManagementDsc Powershell module
      win_psmodule:
        name: ComputerManagementDsc
        state: present
      retries: 10
      delay: 10

    - name: Enable Remote Desktop
      win_dsc:
        resource_name: RemoteDesktopAdmin
        IsSingleInstance : 'yes'
        Ensure: present
        UserAuthentication: Secure

- name: Configure disk
  hosts: dev
  tasks:
    - name: Resize standard partition to it's maximum size
      community.windows.win_partition:
        drive_letter: C
        partition_size: -1